import fs from "node:fs";
import path from "node:path";
import { loadConfig } from "../config.js";
import { changeSet, changedFiles, git, hasChanges, isGitRepo, shortSha } from "../git.js";
import { matchesAny } from "../fsutil.js";
import { formatUsage, runClaude } from "../claude.js";
import { ARTIFACT_GLOBS, cleanAgentAnswer, createRunDir, findService, readStory, writeTools } from "../run.js";
import { createMergeRequest, gitlabContext } from "../scm/gitlab.js";
import { log } from "../log.js";

export interface GenerateOptions {
  cwd: string;
  service: string;
  servicePath?: string;
  base?: string;
  head?: string;
  storyFile?: string;
  push?: boolean;
  dryRun?: boolean;
}

const FOOTER = "\n\n---\nGenerated by qa-sentinel. A QA engineer must review before merge.";

export async function generateCommand(o: GenerateOptions): Promise<void> {
  const cwd = path.resolve(o.cwd);
  const c = loadConfig(cwd);
  const service = findService(c, o.service, cwd, o.servicePath);
  const repo = path.resolve(cwd, service.path);
  if (!isGitRepo(repo)) throw new Error(`${repo} is not a git repository`);
  if (!isGitRepo(cwd)) throw new Error(`The test repo (${cwd}) must be a git repository`);
  if (hasChanges(cwd) && !o.dryRun) throw new Error("The test repo has uncommitted changes; commit or stash them first.");

  const head = o.head ?? "HEAD";
  // GitLab sends 0000… as the "before" SHA for new branches; fall back to the previous commit.
  const base = !o.base || /^0+$/.test(o.base) ? `${head}~1` : o.base;
  const cs = changeSet(repo, base, head);
  const relevant = cs.files.filter((f) => !matchesAny(f, c.agent.skipPaths));
  if (relevant.length === 0) {
    log.ok("no test-relevant changes; nothing to generate");
    return;
  }

  const sha = shortSha(repo, head);
  const branch = `qa-sentinel/${service.name}-${sha}`;
  const run = createRunDir(cwd, `gen-${service.name}`);
  fs.writeFileSync(path.join(run.dir, "change.diff"), cs.diff);
  fs.writeFileSync(path.join(run.dir, "story.md"), readStory({ storyFile: o.storyFile }));
  fs.writeFileSync(
    path.join(run.dir, "context.json"),
    JSON.stringify(
      { kind: "generate", service, serviceRepo: service.path, base, head, sha, changedFiles: relevant, maxFixAttempts: c.agent.maxFixAttempts },
      null,
      2,
    ),
  );

  if (!o.dryRun) git(cwd, ["checkout", "-B", branch]);
  log.step(`${service.name}@${sha}: generating API tests on branch ${branch}`);

  const prompt = [
    "Use the generate-api-tests skill.",
    `Run context: ${run.rel}/context.json, diff: ${run.rel}/change.diff, story: ${run.rel}/story.md.`,
    `Run only the specs you touched with: ${c.tests.api.runCommand} <spec paths>.`,
    "Your final answer must be the merge request summary in markdown (the format in the skill).",
  ].join("\n");

  const res = await runClaude({
    cwd,
    prompt,
    maxTurns: c.agent.maxTurns.generate,
    allowedTools: writeTools(c),
    addDirs: [repo],
    model: c.agent.model,
    dryRun: o.dryRun,
  });
  if (!res.ok) throw new Error(`Generation failed: ${res.result.slice(0, 500)}`);

  const usage = formatUsage(res);
  const summary = `${cleanAgentAnswer(res.result)}${FOOTER}${usage ? ` (${usage})` : ""}`;
  fs.writeFileSync(path.join(run.dir, "summary.md"), summary);
  fs.writeFileSync(path.join(cwd, "qa-sentinel-summary.md"), summary);

  if (o.dryRun) {
    log.ok("dry run complete");
    return;
  }

  // Never commit run artifacts, test output or the summary file.
  const changed = changedFiles(cwd).filter((f) => !matchesAny(f, ARTIFACT_GLOBS));
  if (changed.length === 0) {
    log.ok("agent made no test changes (existing coverage judged sufficient)");
    return;
  }
  git(cwd, ["add", "--", ...changed]);
  git(cwd, ["commit", "-m", `test(${service.name}): QA agent updates for ${sha}\n\nGenerated by qa-sentinel from ${service.name}@${sha}.`]);
  log.ok(`committed ${changed.length} file(s) on ${branch}`);

  if (!o.push) {
    log.info(`Review locally, then push ${branch} and open a merge request (or rerun with --push).`);
    return;
  }
  git(cwd, ["push", "-u", "origin", branch, "--force-with-lease"]);
  const ctx = gitlabContext(c.ci.gitlabUrl);
  const project = c.ci.testRepoProject ?? process.env.CI_PROJECT_ID;
  if (!ctx || !project) {
    log.warn("pushed; set QA_SENTINEL_GITLAB_TOKEN and ci.testRepoProject to open the MR automatically");
    return;
  }
  const mr = await createMergeRequest(ctx, project, {
    source: branch,
    target: c.ci.targetBranch,
    title: `QA agent: tests for ${service.name}@${sha}`,
    description: summary,
    labels: ["qa-agent", `service::${service.name}`],
  });
  log.ok(`merge request opened: ${mr.web_url}`);
}
