// Shared helpers for the ShopLite sandbox scripts (no dependencies beyond qa-sentinel's own).
import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import YAML from "yaml";
import { SCENARIOS, applyEdits } from "./scenarios.mjs";

export const HERE = path.dirname(fileURLToPath(import.meta.url));
export const CLI = path.resolve(HERE, "../../dist/cli.js");
export const SERVICES = ["orders-service", "payments-service", "notifications-service"];
export const TEST_REPO = "qa-tests";

export const log = (...a) => console.log("›", ...a);
export const die = (msg) => {
  console.error(`✗ ${redact(msg)}`);
  process.exit(1);
};

/** Remove credentials from anything we print: push URLs, tokens and keys (errors from git echo the full URL). */
export function redact(text) {
  let out = String(text ?? "")
    .replace(/(\/\/[^/:@\s]+:)[^@\s]+@/g, "$1***@")
    .replace(/glpat-[\w.-]+/g, "glpat-***")
    .replace(/sk-ant-[\w-]+/g, "sk-ant-***");
  for (const k of ["GITLAB_TOKEN", "ANTHROPIC_API_KEY", "JIRA_API_TOKEN"]) {
    const v = process.env[k];
    if (v && v.length >= 8) out = out.split(v).join("***");
  }
  return out;
}

export function sh(cmd, args, opts = {}) {
  try {
    return execFileSync(cmd, args, { encoding: "utf8", stdio: opts.quiet === false ? "inherit" : ["ignore", "pipe", "pipe"], ...opts }).trim();
  } catch (e) {
    const detail = [e.stderr, e.stdout].filter(Boolean).map(String).join("\n").trim();
    throw new Error(redact(`${cmd} ${args[0] ?? ""} failed (exit ${e.status ?? "?"})${detail ? `:\n${detail}` : ""}`));
  }
}
export const git = (cwd, ...args) => sh("git", args, { cwd });

export function copyDir(src, dst) {
  fs.mkdirSync(dst, { recursive: true });
  fs.cpSync(src, dst, { recursive: true });
}

export function commitAll(cwd, msg, author = "ShopLite Dev <dev@shoplite.test>") {
  git(cwd, "add", "-A");
  const [name, email] = author.match(/^(.*) <(.*)>$/).slice(1);
  git(cwd, "-c", `user.name=${name}`, "-c", `user.email=${email}`, "commit", "-q", "-m", msg);
}

export function scenario(id) {
  const s = SCENARIOS.find((x) => x.id.toLowerCase() === String(id).toLowerCase());
  if (!s) die(`unknown scenario "${id}". Known: ${SCENARIOS.map((x) => x.id).join(", ")}`);
  return s;
}

/** Make the developer's change for a scenario on a new branch in a service checkout and commit it. */
export function makeChange(serviceDir, s, { storyKey } = {}) {
  git(serviceDir, "checkout", "-q", "-B", s.branch);
  applyEdits(
    (f) => fs.readFileSync(path.join(serviceDir, f), "utf8"),
    (f, c) => fs.writeFileSync(path.join(serviceDir, f), c),
    s.edits,
  );
  commitAll(serviceDir, `${storyKey ?? s.storyKey ?? s.id}: ${s.title.replace(/^SHOP-\d+:\s*/, "")}`);
}

export function serviceCi(group) {
  return `# ShopLite service pipeline: qa-sentinel gap report on MRs, test generation trigger after merge.
include:
  - project: "${group}/${TEST_REPO}"
    ref: main
    file: "ci/qa-sentinel/service.gitlab-ci.yml"

variables:
  QA_TESTS_PROJECT: "${group}/${TEST_REPO}"
`;
}

export function testsCi(group) {
  return `# ShopLite test repo pipeline (generated by sandbox/shoplite).
include:
  - local: "ci/qa-sentinel/tests.gitlab-ci.yml"

variables:
  # Start the three services + gateway for every test job (see qa-env/start.sh).
  QA_ENV_START: "source qa-env/start.sh"
  QA_ENV_GROUP: "${group}"
`;
}

/**
 * Lockfiles record where each package was downloaded from. On a machine with a private npm mirror
 * (company Nexus/Artifactory) those URLs point at the mirror, which CI runners can't reach, and they leak
 * the mirror's hostname into the repo. Rewrite them to the public registry; the integrity hashes are unchanged.
 */
export function publicLockfile(dir) {
  const file = path.join(dir, "package-lock.json");
  if (!fs.existsSync(file)) return 0;
  let n = 0;
  const text = fs.readFileSync(file, "utf8").replace(
    /"resolved": "https?:\/\/(?!registry\.npmjs\.org\/)[^"]*?\/((?:@[^/"]+\/)?[^/"@]+\/-\/[^/"]+\.tgz)"/g,
    (_m, tail) => {
      n++;
      return `"resolved": "https://registry.npmjs.org/${tail}"`;
    },
  );
  if (n) {
    fs.writeFileSync(file, text);
    log(`${path.basename(dir)}: lockfile URLs pointed at registry.npmjs.org (${n} from a private mirror)`);
  }
  const left = (text.match(/"resolved": "https?:\/\/(?!registry\.npmjs\.org\/)[^"]+"/g) ?? []).length;
  if (left) die(`${file} still has ${left} download URL(s) outside registry.npmjs.org; CI could not install them.`);
  return n;
}

/** Create the three service repos (with lockfiles) in work/. */
export function buildServices(work, { group } = {}) {
  for (const svc of SERVICES) {
    const dir = path.join(work, svc);
    if (fs.existsSync(dir)) fs.rmSync(dir, { recursive: true, force: true });
    copyDir(path.join(HERE, "services", svc), dir);
    if (group) fs.writeFileSync(path.join(dir, ".gitlab-ci.yml"), serviceCi(group));
    log(`${svc}: npm install (lockfile)`);
    sh("npm", ["install", "--no-audit", "--no-fund", "--silent"], { cwd: dir });
    publicLockfile(dir);
    git(dir, "init", "-q", "-b", "main");
    commitAll(dir, "ShopLite: initial service");
  }
}

/** Create the test repo with qa-sentinel init, the sandbox tests and QA env, and a configured qa-sentinel.config.yaml. */
export function buildTests(work, o = {}) {
  const dir = path.join(work, TEST_REPO);
  if (fs.existsSync(dir)) fs.rmSync(dir, { recursive: true, force: true });
  fs.mkdirSync(dir, { recursive: true });
  if (!fs.existsSync(CLI)) die("qa-sentinel is not built. Run `npm install && npm run build` in the qa-sentinel repo first.");
  log(`${TEST_REPO}: qa-sentinel init (level ${o.level ?? "intelligence"})`);
  sh("node", [CLI, "init", "--yes", "--mode", "scratch", "--ci", "gitlab", "--level", o.level ?? "intelligence", "--workspace", "..", "--name", "shoplite-tests"], { cwd: dir });
  fs.rmSync(path.join(dir, "tests/api/example"), { recursive: true, force: true });
  copyDir(path.join(HERE, "tests-extra"), dir);
  configure(dir, o);
  if (o.group) fs.writeFileSync(path.join(dir, ".gitlab-ci.yml"), testsCi(o.group));
  log(`${TEST_REPO}: npm install (lockfile)`);
  sh("npm", ["install", "--no-audit", "--no-fund", "--silent"], { cwd: dir });
  publicLockfile(dir);
  git(dir, "init", "-q", "-b", "main");
  commitAll(dir, "ShopLite: test repo set up with qa-sentinel");
  return dir;
}

/** Fill in the parts of qa-sentinel.config.yaml init cannot know about ShopLite. */
export function configure(dir, o = {}) {
  const file = path.join(dir, "qa-sentinel.config.yaml");
  const doc = YAML.parseDocument(fs.readFileSync(file, "utf8"));
  const c = doc.toJS();
  c.level = o.level ?? c.level;
  c.workspace.services = SERVICES.map((name) => ({
    name,
    path: `../${name}`,
    openapi: "openapi.yaml",
    ...(o.group ? { gitlabProject: `${o.group}/${name}` } : {}),
    dependsOn: name === "orders-service" ? ["payments-service", "notifications-service"] : [],
    version: { path: `/${name.replace(/-service$/, "")}/version`, field: "commit" },
  }));
  // The local QA environment (qa-env/start.sh); feature readiness checks deployments here.
  c.environments = { ...(c.environments ?? {}), local: { baseUrl: "http://127.0.0.1:8080", description: "ShopLite started by qa-env/start.sh" } };
  c.tests.api.baseUrlEnv = "QA_BASE_URL";
  c.guardrails.allowedHosts = ["localhost", "127.0.0.1", "example.com", "example.test", "shoplite.test"];
  if (o.group) {
    c.ci.gitlabUrl = o.gitlabUrl ?? "https://gitlab.com";
    c.ci.testRepoProject = `${o.group}/${TEST_REPO}`;
  }
  if (o.jira?.baseUrl) {
    c.requirements.source = "jira";
    c.requirements.jira = {
      ...c.requirements.jira,
      baseUrl: o.jira.baseUrl,
      projectKeys: [o.jira.project],
      approvedStatuses: ["In Progress", "Selected for Development", "Ready for Development", "Done"],
    };
    // With Jira connected, publish the gap report on the story too (and keep the MR comment).
    c.reporting = { ...(c.reporting ?? {}), targets: ["gitlab-mr", "jira"] };
    // With Jira connected, publish the gap report on the story too (and keep the MR comment).
    c.reporting = { ...(c.reporting ?? {}), targets: ["gitlab-mr", "jira"] };
  }
  fs.writeFileSync(file, "# qa-sentinel configuration for the ShopLite sandbox.\n" + YAML.stringify(c, { lineWidth: 100 }));
}

export function loadState(work) {
  const f = path.join(work, ".shoplite-state.json");
  return fs.existsSync(f) ? JSON.parse(fs.readFileSync(f, "utf8")) : {};
}
export function saveState(work, s) {
  fs.mkdirSync(work, { recursive: true });
  fs.writeFileSync(path.join(work, ".shoplite-state.json"), JSON.stringify(s, null, 2));
}

/** Parse --flag value / --flag pairs. */
export function flags(argv) {
  const out = { _: [] };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith("--")) {
      const k = a.slice(2);
      const v = argv[i + 1] && !argv[i + 1].startsWith("--") ? argv[++i] : true;
      out[k] = v;
    } else out._.push(a);
  }
  return out;
}

// ---------- GitLab REST ----------
export function gitlab(env = process.env) {
  const url = (env.GITLAB_URL || "https://gitlab.com").replace(/\/$/, "");
  const token = env.GITLAB_TOKEN;
  if (!token) die("Set GITLAB_TOKEN (a personal access token with the api and write_repository scopes).");
  const api = async (method, route, body) => {
    let res;
    for (let attempt = 1; ; attempt++) {
      try {
        res = await fetch(`${url}/api/v4${route}`, {
          method,
          headers: { "PRIVATE-TOKEN": token, "content-type": "application/json" },
          body: body ? JSON.stringify(body) : undefined,
        });
        break;
      } catch (e) {
        // Node's fetch says only "fetch failed"; the reason (DNS, proxy, TLS certificate…) is in e.cause.
        const c = e.cause ?? {};
        const why = [c.code, c.message].filter(Boolean).join(": ") || e.message;
        if (attempt < 3 && /ECONNRESET|ETIMEDOUT|EAI_AGAIN|UND_ERR_SOCKET|UND_ERR_CONNECT_TIMEOUT/.test(why)) {
          await new Promise((r) => setTimeout(r, 1000 * attempt));
          continue;
        }
        const hint = /CERT|certificate|SELF_SIGNED|UNABLE_TO/i.test(why)
          ? " (TLS: this network inspects HTTPS. Node doesn't use the macOS keychain; see docs/SANDBOX.md › Troubleshooting)"
          : /ENOTFOUND|EAI_AGAIN/.test(why)
            ? " (DNS: check GITLAB_URL and your network)"
            : "";
        throw new Error(`GitLab ${method} ${url}/api/v4${route} failed: ${why}${hint}`);
      }
    }
    const text = await res.text();
    const data = text ? JSON.parse(text) : undefined;
    if (!res.ok) {
      const err = new Error(`GitLab ${method} ${route}: ${res.status} ${text.slice(0, 300)}`);
      err.status = res.status;
      err.data = data;
      throw err;
    }
    return data;
  };
  const host = new URL(url).host;
  const remote = (projectPath) => `${new URL(url).protocol}//oauth2:${encodeURIComponent(token)}@${host}/${projectPath}.git`;
  return { url, api, remote, enc: (p) => encodeURIComponent(p) };
}
