export { ConfigSchema, loadConfig, writeConfig, type Config } from "./config.js";
export { detectProject, discoverServices } from "./detect.js";
export { initCommand } from "./commands/init.js";
export { gapReportCommand } from "./commands/gapReport.js";
export { generateCommand } from "./commands/generate.js";
export { learnCommand } from "./commands/learn.js";
export { runChecks } from "./commands/doctor.js";
export { TestPlanSchema, type TestPlan } from "./plan/schema.js";
export { validatePlan } from "./plan/validate.js";
export { riskOf, applyRisk } from "./plan/risk.js";
export { diffSpecs } from "./analysis/contractDiff.js";
export type { AgentEngine, AgentTask, AgentResult } from "./engines/AgentEngine.js";
export { ClaudeCodeEngine } from "./engines/ClaudeCodeEngine.js";
