import type { Finding } from "./guardrails.js";
import { findingsMarkdown } from "./guardrails.js";
import type { RequirementSnapshot } from "./requirements.js";
import { requirementsLine } from "./requirements.js";
import type { Discrepancy, VerificationReport } from "./verification.js";
import { STATUS_BADGE, verificationMarkdown } from "./verification.js";

export interface MrDescriptionInput {
  service: string;
  sha: string;
  version: string;
  requirements: RequirementSnapshot;
  verification: VerificationReport;
  findings: Finding[];
  discrepancies: Discrepancy[];
  agentSummary: string;
  usage: string;
  runId: string;
}

/**
 * The MR description. Facts come first and are produced by qa-sentinel itself (verification, policy checks,
 * requirement provenance, unresolved discrepancies). The agent's own narrative comes last and is labelled as such.
 */
export function mrDescription(i: MrDescriptionInput): string {
  const warnings = i.findings.filter((f) => f.level === "warning");
  const parts = [
    `## QA agent: ${i.service}@${i.sha.slice(0, 8)} · ${STATUS_BADGE[i.verification.status]}`,
    "",
    requirementsLine(i.requirements),
    "",
    verificationMarkdown(i.verification),
  ];
  if (i.discrepancies.length) {
    parts.push(
      "",
      `### ⚠️ Unresolved product discrepancies (${i.discrepancies.length}, not executed as passing tests)`,
      "These tests encode the requirement, but the product currently behaves differently. They are marked fixme/skip so they do not fail the build. **A human must decide: fix the product or change the requirement.**",
      "",
      "| Test | File | Note |",
      "| --- | --- | --- |",
      ...i.discrepancies.map((d) => `| ${d.test} | \`${d.file}\` | ${d.note ?? "_no QA-AGENT note: ask the author agent why it is skipped_"} |`),
    );
  }
  if (warnings.length) parts.push("", "### Policy warnings", findingsMarkdown(warnings));
  parts.push(
    "",
    "### Agent notes",
    "_Written by the agent. Claims about test results here are superseded by the verification table above._",
    "",
    i.agentSummary.replace(/^##\s+QA agent:.*$/m, "").trim(),
    "",
    "---",
    `Generated by qa-sentinel ${i.version} (run \`${i.runId}\`${i.usage ? `, ${i.usage}` : ""}). A QA engineer must review before merge.`,
  );
  return parts.join("\n");
}
