import type { Finding } from "./guardrails.js";
import { findingsMarkdown } from "./guardrails.js";
import type { RequirementSnapshot } from "./requirements.js";
import { requirementsLine } from "./requirements.js";
import type { Discrepancy, VerificationReport } from "./verification.js";
import { STATUS_BADGE, verificationMarkdown } from "./verification.js";
import type { ContractDiff } from "./analysis/contractDiff.js";
import { contractDiffMarkdown } from "./analysis/contractDiff.js";
import type { RiskLevel, TestPlan } from "./plan/schema.js";
import type { RiskedChange } from "./plan/risk.js";
import { RISK_BADGE, decisionTable } from "./plan/render.js";

export interface MrDescriptionInput {
  /** Named environment the tests ran against (from `environments`), if any. */
  environment?: string;
  service: string;
  sha: string;
  version: string;
  requirements: RequirementSnapshot;
  verification: VerificationReport;
  findings: Finding[];
  discrepancies: Discrepancy[];
  /** Requirement → test matrix built from test tags (empty when the story has no AC). */
  traceability?: string;
  /** Independent test review section (empty when not run). */
  review?: string;
  agentSummary: string;
  usage: string;
  runId: string;
  /** The validated plan behind the change (decision table, risk, contract diff). */
  plan?: { plan: TestPlan; risked: { changes: RiskedChange[]; overall: RiskLevel }; contract: ContractDiff; specPath?: string; corrections: string[] };
}

/**
 * The MR description. Facts come first and are produced by qa-sentinel itself (verification, policy checks,
 * requirement provenance, unresolved discrepancies). The agent's own narrative comes last and is labelled as such.
 */
export function mrDescription(i: MrDescriptionInput): string {
  const warnings = i.findings.filter((f) => f.level === "warning");
  const parts = [
    `## QA agent: ${i.service}@${i.sha.slice(0, 8)} · ${STATUS_BADGE[i.verification.status]}${i.plan ? ` · ${RISK_BADGE[i.plan.risked.overall]} risk` : ""}`,
    "",
    requirementsLine(i.requirements),
    "",
    ...(i.environment ? [`**Environment:** tests ran against \`${i.environment}\` before this MR was opened.`, ""] : []),
    verificationMarkdown(i.verification),
  ];
  if (i.plan) {
    parts.push("", "### Plan (validated by qa-sentinel)", i.plan.plan.verdict, "", decisionTable(i.plan.plan, i.plan.risked.changes));
    if (i.plan.corrections.length) parts.push("", ...i.plan.corrections.map((x) => `- correction: ${x}`));
    parts.push("", contractDiffMarkdown(i.plan.contract, i.plan.specPath));
  }
  if (i.discrepancies.length) {
    parts.push(
      "",
      `### ⚠️ Unresolved product discrepancies (${i.discrepancies.length}, not executed as passing tests)`,
      "These tests encode the requirement, but the product currently behaves differently. They are marked fixme/skip so they do not fail the build. **A human must decide: fix the product or change the requirement.**",
      "",
      "| Test | File | Note |",
      "| --- | --- | --- |",
      ...i.discrepancies.map((d) => `| ${d.test} | \`${d.file}\` | ${d.note ?? "_no QA-AGENT note: ask the author agent why it is skipped_"} |`),
    );
  }
  if (i.traceability) parts.push("", i.traceability);
  if (i.review) parts.push("", i.review);
  if (warnings.length) parts.push("", "### Policy warnings", findingsMarkdown(warnings));
  parts.push(
    "",
    "### Agent notes",
    "_Written by the agent. Claims about test results here are superseded by the verification table above._",
    "",
    i.agentSummary.replace(/^##\s+QA agent:.*$/m, "").trim(),
    "",
    "---",
    `Generated by qa-sentinel ${i.version} (run \`${i.runId}\`${i.usage ? `, ${i.usage}` : ""}). A QA engineer must review before merge.`,
  );
  return parts.join("\n");
}
